package io.paperagent.v2.persistence;

public enum PersistenceErrorCode {
    INVALID_ARGUMENT,
    NOT_FOUND,
    CONFLICTING_REPLAY,
    BOOTSTRAP_PARTIAL_STATE,
    STALE_VERSION,
    TASK_FRAME_MISMATCH,
    PLAN_VALIDATION_FAILED,
    EVENT_SEQUENCE_NOT_MONOTONIC,
    CHECKPOINT_VALIDATION_FAILED,
    LEASE_HELD,
    LEASE_NOT_HELD,
    LEASE_TOKEN_INVALID,
    LEASE_EXPIRED,
    IDEMPOTENCY_FINGERPRINT_CONFLICT,
    IDEMPOTENCY_ILLEGAL_TRANSITION
}
